# LangGraph Basics 01: StateGraph, Nodes & Edges
# Models: Ollama (local) + Groq (free cloud)
# Use Case: Structured Blog Post Generation Pipeline

from dotenv import load_dotenv
from typing import TypedDict
from langchain_ollama import ChatOllama
from langchain_groq import ChatGroq
from langgraph.graph import StateGraph, START, END

load_dotenv()

# ── Model Setup ──────────────────────────────────────────────
ollama_llm = ChatOllama(model="mistral:7b", temperature=0.3)
groq_llm   = ChatGroq(model="llama3-8b-8192", temperature=0.3)

# ── 1. Define State Schema ───────────────────────────────────
# State is a TypedDict — shared data passed between all nodes
class BlogState(TypedDict):
    topic: str        # Input
    outline: str      # Generated by node 1
    draft: str        # Generated by node 2
    final: str        # Generated by node 3
    word_count: int   # Computed in node 3

# ── 2. Define Nodes ──────────────────────────────────────────
# Each node: receives full state, returns ONLY the fields it updates

def generate_outline(state: BlogState) -> dict:
    """Node 1: Generate a blog outline using Groq (fast)"""
    print("  [Node 1] Generating outline...")
    response = groq_llm.invoke(
        f"Create a concise 3-point outline for a blog post about: {state['topic']}"
    )
    return {"outline": response.content}

def write_draft(state: BlogState) -> dict:
    """Node 2: Write a draft using Ollama (local)"""
    print("  [Node 2] Writing draft...")
    response = ollama_llm.invoke(
        f"Write a short blog post (150 words) based on this outline:\n{state['outline']}\n\nTopic: {state['topic']}"
    )
    return {"draft": response.content}

def polish_content(state: BlogState) -> dict:
    """Node 3: Polish the draft using Groq (fast)"""
    print("  [Node 3] Polishing content...")
    response = groq_llm.invoke(
        f"Improve this blog post — make it more engaging and professional:\n\n{state['draft']}"
    )
    final = response.content
    return {"final": final, "word_count": len(final.split())}

def quality_check(state: BlogState) -> dict:
    """Node 4: Log quality metrics (no LLM needed)"""
    print(f"  [Node 4] Quality check — word count: {state['word_count']}")
    return {}  # No state changes, just side effects

# ── 3. Build the Graph ───────────────────────────────────────
print("=" * 50)
print("BUILDING LANGGRAPH PIPELINE")
print("=" * 50)

graph = StateGraph(BlogState)

# Add nodes
graph.add_node("outline",       generate_outline)
graph.add_node("draft",         write_draft)
graph.add_node("polish",        polish_content)
graph.add_node("quality_check", quality_check)

# Add edges (defines execution order)
graph.add_edge(START,           "outline")
graph.add_edge("outline",       "draft")
graph.add_edge("draft",         "polish")
graph.add_edge("polish",        "quality_check")
graph.add_edge("quality_check", END)

app = graph.compile()

# ── 4. Run the Graph ─────────────────────────────────────────
print("\n" + "=" * 50)
print("RUNNING PIPELINE")
print("=" * 50)

result = app.invoke({"topic": "Why LangGraph is the future of AI agents"})

print(f"\nTopic     : {result['topic']}")
print(f"Word Count: {result['word_count']}")
print(f"\nOutline:\n{result['outline']}")
print(f"\nFinal Post (first 400 chars):\n{result['final'][:400]}...")

# ── 5. Inspect Graph Structure ───────────────────────────────
print("\n" + "=" * 50)
print("GRAPH STRUCTURE")
print("=" * 50)
print("Nodes:", list(graph.nodes.keys()))

# ── 6. Run with Different Topic ──────────────────────────────
print("\n" + "=" * 50)
print("SECOND RUN — DIFFERENT TOPIC")
print("=" * 50)

result2 = app.invoke({"topic": "Getting started with Ollama for local AI development"})
print(f"Topic: {result2['topic']}")
print(f"Words: {result2['word_count']}")
print(f"Preview: {result2['final'][:200]}...")
